/*******************************************************************************
  ZGP Application configuration Header File

  Company:
    Microchip Technology Inc.

  File Name:
    zgpAppConfig.h

  Summary:
    This file contains the zgp - application configuration implementation

  Description:
    This file contains the zgp - application configuration implementation
 *******************************************************************************/

// DOM-IGNORE-BEGIN
/*******************************************************************************
* Copyright (C) 2018 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
*******************************************************************************/
// DOM-IGNORE-END

#ifndef _ZGPAPPCONFIG_H
#define _ZGPAPPCONFIG_H

#ifdef _GREENPOWER_SUPPORT_
#if APP_ZGP_DEVICE_TYPE == APP_ZGP_DEVICE_TYPE_COMBO_BASIC
#ifndef ZGP_DISABLE_TRANSLATION_TABLE
#include <z3device/common/include/zgpAppInterface.h>

/**************************************************************************//**
Defines Section
******************************************************************************/
//#define ZGP_LW_TRANSLATION_TABLE

#define UNSPECIFIED_CLUSTER_ID 0xFFFF
#define UNSPECIFIED_CMD_ID   0xFF
#define UNSPECIFIED_LENGTH  0xFE
#define UNSPECIFIED_PAYLOAD_LENGTH 0xFF

#ifndef ZGP_GPD_ZCL_CMD_MAPPING_PAYLOADLENGTH
#define ZGP_GPD_ZCL_CMD_MAPPING_PAYLOADLENGTH 4
#endif

/**************************************************************************//**
ZGP command Id to ZCL command id mapping
******************************************************************************/
#define ZGP_ONOFF_CMD_ID_ON_MAPPING                {ZGP_ONOFF_CMD_ID_ON,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_ON,0,0x00,0x00}
#define ZGP_ONOFF_CMD_ID_OFF_MAPPING                 {ZGP_ONOFF_CMD_ID_OFF,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_OFF,0,0x00}
#define ZGP_ONOFF_CMD_ID_TOGGLE_MAPPING             {ZGP_ONOFF_CMD_ID_TOGGLE,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_TOGGLE,0,0x00}
#define ZGP_IDENTIFY_CMD_ID_IDENTIFY_MAPPING         {ZGP_IDENTIFY_CMD_ID_IDENTIFY,IDENTIFY_CLUSTER_ID,ZCL_IDENTIFY_CLUSTER_IDENTIFY_COMMAND_ID,2,ZCL_IDENTIFY_PAYLOAD}
#define ZGP_LC_CMD_ID_LEVEL_CONTROL_STOP_MAPPING     {ZGP_LC_CMD_ID_LEVEL_CONTROL_STOP,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_STOP_COMMAND_ID,0,0x00}
#define ZGP_LC_CMD_ID_LEVEL_CONTROL_MOVE_UP_MAPPING     {ZGP_LC_CMD_ID_MOVE_UP,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_MOVE_COMMAND_ID,2,0x00,0x00}
#define ZGP_LC_CMD_ID_LEVEL_CONTROL_MOVE_DOWN_MAPPING     {ZGP_LC_CMD_ID_MOVE_DOWN,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_MOVE_COMMAND_ID,2,0x01,0x00}
#define ZGP_LC_CMD_ID_LEVEL_CONTROL_STEP_UP_MAPPING     {ZGP_LC_CMD_ID_STEP_UP,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_STEP_COMMAND_ID,4,0x00,0x00,0x00,0x00}
#define ZGP_LC_CMD_ID_LEVEL_CONTROL_STEP_DOWN_MAPPING     {ZGP_LC_CMD_ID_STEP_DOWN,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_STEP_COMMAND_ID,4,0x01,0x00,0x00, 0x00}
#define ZGP_LC_CMD_ID_LEVEL_CONTROL_MOVE_DOWN_WITH_ONOFF_MAPPING     {ZGP_LC_CMD_ID_MOVE_DOWN_WITH_ONOFF,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_MOVE_W_ONOFF_COMMAND_ID,2,0x00,0x00}
#define ZGP_LC_CMD_ID_LEVEL_CONTROL_MOVE_UP_WITH_ONOFF_MAPPING     {ZGP_LC_CMD_ID_MOVE_UP_WITH_ONOFF,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_MOVE_W_ONOFF_COMMAND_ID,2,0x01,0x00}
#define ZGP_LC_CMD_ID_LEVEL_CONTROL_STEP_DOWN_WITH_ONOFF_MAPPING     {ZGP_LC_CMD_ID_STEP_DOWN_WITH_ONOFF,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_STEP_W_ONOFF_COMMAND_ID,2,0x00,0x00}
#define ZGP_LC_CMD_ID_LEVEL_CONTROL_STEP_UP_WITH_ONOFF_MAPPING     {ZGP_LC_CMD_ID_STEP_UP_WITH_ONOFF,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_STEP_W_ONOFF_COMMAND_ID,2,0x01,0x00}
#define ZGP_SCENE_CMD_ID_RECALLSCENE0_MAPPING        {ZGP_SCENE_CMD_ID_RECALLSCENE0,SCENES_CLUSTER_ID,ZCL_SCENES_CLUSTER_RECALL_SCENE_COMMAND_ID,UNSPECIFIED_LENGTH,0x00,0x00}
#define ZGP_SCENE_CMD_ID_STORESCENE0_MAPPING         {ZGP_SCENE_CMD_ID_STORESCENE0,SCENES_CLUSTER_ID,ZCL_SCENES_CLUSTER_STORE_SCENE_COMMAND_ID,UNSPECIFIED_LENGTH,0x00,0x00}
#define ZGP_CC_CMD_ID_MOVE_HUE_STOP_MAPPING         {ZGP_CC_CMD_ID_MOVE_HUE_STOP,COLOR_CONTROL_CLUSTER_ID,MOVE_TO_HUE_COMMAND_ID,2,ZCL_COLOR_CONTROL_STOP_PAYLOAD}
#define ZGP_CC_CMD_ID_MOVE_SATURATION_STOP_MAPPING   {ZGP_CC_CMD_ID_MOVE_SATURATION_STOP,COLOR_CONTROL_CLUSTER_ID,MOVE_TO_SATURATION_COMMAND_ID,2,ZCL_COLOR_CONTROL_STOP_PAYLOAD}
#define ZGP_ATTR_REPORT_CMD_ID_MAPPING             {ZGP_ATTRIBUTE_REPORT_CMD_ID, UNSPECIFIED_CLUSTER_ID, ZCL_REPORT_ATTRIBUTES_COMMAND_ID, UNSPECIFIED_LENGTH, 0x00}
#define ZGP_MANUFAC_SPEC_ATTR_REPORT_CMD_ID_MAPPING        {ZGP_MANU_SPEC_ATTR_REPORT_CMD_ID, UNSPECIFIED_CLUSTER_ID, ZCL_REPORT_ATTRIBUTES_COMMAND_ID, UNSPECIFIED_LENGTH, 0x00}
#define ZGP_MULTI_CLUSTER_ATTR_REPORT_CMD_ID_MAPPING       {ZGP_MULTI_CLUSTER_ATTR_REPORT_CMD_ID, UNSPECIFIED_CLUSTER_ID, ZCL_REPORT_ATTRIBUTES_COMMAND_ID, UNSPECIFIED_LENGTH, 0x00}
#define ZGP_MANUFAC_SPEC_MULTI_CLUSTER_ATTR_REPORT_CMD_ID_MAPPING      {ZGP_MANU_SPEC_MULTI_CLUSTER_ATTR_REPORT_CMD_ID, UNSPECIFIED_CLUSTER_ID, ZCL_REPORT_ATTRIBUTES_COMMAND_ID, UNSPECIFIED_LENGTH, 0x00}
#define ZGP_ZCL_TUNNELING_CMD_ID_MAPPING             {ZGP_ZCL_TUNNELING_CMD_ID, UNSPECIFIED_CLUSTER_ID, UNSPECIFIED_CMD_ID, UNSPECIFIED_PAYLOAD_LENGTH, 0x00}
#define ZGP_COMPACT_REPORT_CMD_ID_MAPPING            {ZGP_COMPACT_ATTR_REPORT_CMD_ID, UNSPECIFIED_CLUSTER_ID, ZCL_REPORT_ATTRIBUTES_COMMAND_ID, UNSPECIFIED_LENGTH, 0x00}

#ifdef ZGP_ENABLE_GENERIC_8_CONTACT_SWITCH_SUPPORT
#if (APP_Z3_DEVICE_TYPE != APP_DEVICE_TYPE_DIMMABLE_LIGHT)
#error ZGP_GENERIC_8_CONTACT_SWITCH is only supported for APP_DEVICE_TYPE_DIMMABLE_LIGHT
#endif
// Generic_8_contact switch
// ************Mapping for 1 contact getting paired**************//
#define ZGP_G8CS_1C_CMD_ID_PRESS_MAPPING                 {ZGP_8_BIT_VECTOR_PRESS,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_TOGGLE,0,0x00}
#define ZGP_G8CS_1C_CMD_ID_RELEASE_MAPPING               {ZGP_8_BIT_VECTOR_RELEASE,UNSPECIFIED_CLUSTER_ID,UNSPECIFIED_CMD_ID,UNSPECIFIED_LENGTH,0x00}
// ************Mapping for 2 contact getting paired**************//
#define ZGP_G8CS_2C_CMD_ID_1ST_CONTACT_PRESS_MAPPING     {ZGP_8_BIT_VECTOR_PRESS,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_ON,0,0x00}
#define ZGP_G8CS_2C_CMD_ID_1ST_CONTACT_RELEASE_MAPPING   {ZGP_8_BIT_VECTOR_RELEASE,UNSPECIFIED_CLUSTER_ID,UNSPECIFIED_CMD_ID,UNSPECIFIED_LENGTH,0x00}
#define ZGP_G8CS_2C_CMD_ID_2ND_CONTACT_PRESS_MAPPING     {ZGP_8_BIT_VECTOR_PRESS,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_OFF,0,0x00}
#define ZGP_G8CS_2C_CMD_ID_2ND_CONTACT_RELEASE_MAPPING   {ZGP_8_BIT_VECTOR_RELEASE,UNSPECIFIED_CLUSTER_ID,UNSPECIFIED_CMD_ID,UNSPECIFIED_LENGTH,0x00}
// ************Mapping for 3 contact getting paired**************//
#define ZGP_G8CS_3C_CMD_ID_1ST_CONTACT_PRESS_MAPPING     {ZGP_8_BIT_VECTOR_PRESS,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_MOVE_COMMAND_ID,2,0x00,0x00}
#define ZGP_G8CS_3C_CMD_ID_1ST_CONTACT_RELEASE_MAPPING   {ZGP_8_BIT_VECTOR_RELEASE,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_STOP_COMMAND_ID,0,0x00}
#define ZGP_G8CS_3C_CMD_ID_2ND_CONTACT_PRESS_MAPPING     {ZGP_8_BIT_VECTOR_PRESS,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_MOVE_COMMAND_ID,2,0x01,0x00}
#define ZGP_G8CS_3C_CMD_ID_2ND_CONTACT_RELEASE_MAPPING   {ZGP_8_BIT_VECTOR_RELEASE,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_STOP_COMMAND_ID,0,0x00}
#define ZGP_G8CS_3C_CMD_ID_3RD_CONTACT_PRESS_MAPPING     {ZGP_8_BIT_VECTOR_PRESS,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_TOGGLE,0,0x00}
#define ZGP_G8CS_3C_CMD_ID_3RD_CONTACT_RELEASE_MAPPING   {ZGP_8_BIT_VECTOR_RELEASE,UNSPECIFIED_CLUSTER_ID,UNSPECIFIED_CMD_ID,UNSPECIFIED_LENGTH,0x00}
// ************Mapping for 4 contact getting paired**************//
#define ZGP_G8CS_4C_CMD_ID_1ST_CONTACT_PRESS_MAPPING     {ZGP_8_BIT_VECTOR_PRESS,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_ON,0,0x00}
#define ZGP_G8CS_4C_CMD_ID_1ST_CONTACT_RELEASE_MAPPING   {ZGP_8_BIT_VECTOR_RELEASE,UNSPECIFIED_CLUSTER_ID,UNSPECIFIED_CMD_ID,UNSPECIFIED_LENGTH,0x00}
#define ZGP_G8CS_4C_CMD_ID_2ND_CONTACT_PRESS_MAPPING     {ZGP_8_BIT_VECTOR_PRESS,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_OFF,0,0x00}
#define ZGP_G8CS_4C_CMD_ID_2ND_CONTACT_RELEASE_MAPPING   {ZGP_8_BIT_VECTOR_RELEASE,UNSPECIFIED_CLUSTER_ID,UNSPECIFIED_CMD_ID,UNSPECIFIED_LENGTH,0x00}
#define ZGP_G8CS_4C_CMD_ID_3RD_CONTACT_PRESS_MAPPING     {ZGP_8_BIT_VECTOR_PRESS,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_MOVE_COMMAND_ID,2,0x00,0x00}
#define ZGP_G8CS_4C_CMD_ID_3RD_CONTACT_RELEASE_MAPPING   {ZGP_8_BIT_VECTOR_RELEASE,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_STOP_COMMAND_ID,0,0x00}
#define ZGP_G8CS_4C_CMD_ID_4TH_CONTACT_PRESS_MAPPING     {ZGP_8_BIT_VECTOR_PRESS,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_MOVE_COMMAND_ID,2,0x01,0x00}
#define ZGP_G8CS_4C_CMD_ID_4TH_CONTACT_RELEASE_MAPPING   {ZGP_8_BIT_VECTOR_RELEASE,LEVEL_CONTROL_CLUSTER_ID,ZCL_LEVEL_CONTROL_CLUSTER_STOP_COMMAND_ID,0,0x00}

// ************Mapping for 1 contact getting paired**************//
#define ZGP_G8CS_ROCKER_1C_CMD_ID_PRESS_MAPPING                 ZGP_G8CS_2C_CMD_ID_1ST_CONTACT_PRESS_MAPPING
#define ZGP_G8CS_ROCKER_1C_CMD_ID_RELEASE_MAPPING               {ZGP_8_BIT_VECTOR_RELEASE,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_OFF,0,0x00}
// ************Mapping for 2 contact getting paired**************//
#define ZGP_G8CS_ROCKER_2C_CMD_ID_1ST_CONTACT_PRESS_MAPPING     ZGP_G8CS_3C_CMD_ID_1ST_CONTACT_PRESS_MAPPING
#define ZGP_G8CS_ROCKER_2C_CMD_ID_1ST_CONTACT_RELEASE_MAPPING   ZGP_G8CS_3C_CMD_ID_1ST_CONTACT_RELEASE_MAPPING
#define ZGP_G8CS_ROCKER_2C_CMD_ID_2ND_CONTACT_PRESS_MAPPING     ZGP_G8CS_3C_CMD_ID_2ND_CONTACT_PRESS_MAPPING
#define ZGP_G8CS_ROCKER_2C_CMD_ID_2ND_CONTACT_RELEASE_MAPPING   ZGP_G8CS_3C_CMD_ID_2ND_CONTACT_RELEASE_MAPPING
#endif
/**************************************************************************//**
ZGP to ZCL command id mapping list for standard GPD devices
******************************************************************************/
#define ZGP_ON_OFF_SWITCH_CMD_LIST       ZGP_ONOFF_CMD_ID_ON_MAPPING, \
                                         ZGP_ONOFF_CMD_ID_OFF_MAPPING, \
                                         ZGP_ONOFF_CMD_ID_TOGGLE_MAPPING

#define ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST ZGP_LC_CMD_ID_LEVEL_CONTROL_STOP_MAPPING, \
                                          ZGP_LC_CMD_ID_LEVEL_CONTROL_MOVE_UP_MAPPING, \
                                          ZGP_LC_CMD_ID_LEVEL_CONTROL_MOVE_DOWN_MAPPING, \
                                          ZGP_LC_CMD_ID_LEVEL_CONTROL_STEP_UP_MAPPING, \
                                          ZGP_LC_CMD_ID_LEVEL_CONTROL_STEP_DOWN_MAPPING, \
                                          ZGP_LC_CMD_ID_LEVEL_CONTROL_MOVE_DOWN_WITH_ONOFF_MAPPING, \
                                          ZGP_LC_CMD_ID_LEVEL_CONTROL_MOVE_UP_WITH_ONOFF_MAPPING, \
                                          ZGP_LC_CMD_ID_LEVEL_CONTROL_STEP_DOWN_WITH_ONOFF_MAPPING, \
                                          ZGP_LC_CMD_ID_LEVEL_CONTROL_STEP_UP_WITH_ONOFF_MAPPING

#define ZGP_COLOR_DIMMER_SWITCH_CMD_LIST ZGP_SCENE_CMD_ID_RECALLSCENE0_MAPPING, \
                                         ZGP_SCENE_CMD_ID_STORESCENE0_MAPPING, \
                                         ZGP_CC_CMD_ID_MOVE_HUE_STOP_MAPPING, \
                                         ZGP_CC_CMD_ID_MOVE_SATURATION_STOP_MAPPING

#define ZGP_ZCL_TUNNELING_CMD_LIST      ZGP_ZCL_TUNNELING_CMD_ID_MAPPING

#define ZGP_ATTR_REPORT_CMD_LIST         ZGP_ATTR_REPORT_CMD_ID_MAPPING, \
                                         ZGP_MANUFAC_SPEC_ATTR_REPORT_CMD_ID_MAPPING, \
                                         ZGP_MULTI_CLUSTER_ATTR_REPORT_CMD_ID_MAPPING, \
                                         ZGP_MANUFAC_SPEC_MULTI_CLUSTER_ATTR_REPORT_CMD_ID_MAPPING

#define ZGP_G8CS_1C_CMD_LIST             ZGP_G8CS_1C_CMD_ID_PRESS_MAPPING, \
                                         ZGP_G8CS_1C_CMD_ID_RELEASE_MAPPING

#define ZGP_G8CS_2C_CMD_LIST             ZGP_G8CS_2C_CMD_ID_1ST_CONTACT_PRESS_MAPPING, \
                                         ZGP_G8CS_2C_CMD_ID_1ST_CONTACT_RELEASE_MAPPING, \
                                         ZGP_G8CS_2C_CMD_ID_2ND_CONTACT_PRESS_MAPPING, \
                                         ZGP_G8CS_2C_CMD_ID_2ND_CONTACT_RELEASE_MAPPING

#define ZGP_G8CS_3C_CMD_LIST             ZGP_G8CS_3C_CMD_ID_1ST_CONTACT_PRESS_MAPPING, \
                                         ZGP_G8CS_3C_CMD_ID_1ST_CONTACT_RELEASE_MAPPING, \
                                         ZGP_G8CS_3C_CMD_ID_2ND_CONTACT_PRESS_MAPPING, \
                                         ZGP_G8CS_3C_CMD_ID_2ND_CONTACT_RELEASE_MAPPING, \
                                         ZGP_G8CS_3C_CMD_ID_3RD_CONTACT_PRESS_MAPPING, \
                                         ZGP_G8CS_3C_CMD_ID_3RD_CONTACT_RELEASE_MAPPING

#define ZGP_G8CS_4C_CMD_LIST             ZGP_G8CS_4C_CMD_ID_1ST_CONTACT_PRESS_MAPPING, \
                                         ZGP_G8CS_4C_CMD_ID_1ST_CONTACT_RELEASE_MAPPING, \
                                         ZGP_G8CS_4C_CMD_ID_2ND_CONTACT_PRESS_MAPPING, \
                                         ZGP_G8CS_4C_CMD_ID_2ND_CONTACT_RELEASE_MAPPING, \
                                         ZGP_G8CS_4C_CMD_ID_3RD_CONTACT_PRESS_MAPPING, \
                                         ZGP_G8CS_4C_CMD_ID_3RD_CONTACT_RELEASE_MAPPING, \
                                         ZGP_G8CS_4C_CMD_ID_4TH_CONTACT_PRESS_MAPPING, \
                                         ZGP_G8CS_4C_CMD_ID_4TH_CONTACT_RELEASE_MAPPING

#define ZGP_G8CS_ROCKER_1C_CMD_LIST      ZGP_G8CS_ROCKER_1C_CMD_ID_PRESS_MAPPING, \
                                         ZGP_G8CS_ROCKER_1C_CMD_ID_RELEASE_MAPPING

#define ZGP_G8CS_ROCKER_2C_CMD_LIST      ZGP_G8CS_ROCKER_2C_CMD_ID_1ST_CONTACT_PRESS_MAPPING, \
                                         ZGP_G8CS_ROCKER_2C_CMD_ID_1ST_CONTACT_RELEASE_MAPPING, \
                                         ZGP_G8CS_ROCKER_2C_CMD_ID_2ND_CONTACT_PRESS_MAPPING, \
                                         ZGP_G8CS_ROCKER_2C_CMD_ID_2ND_CONTACT_RELEASE_MAPPING

#define ZGP_ON_OFF_SWITCH_CMD_LIST_SIZE 3
#define ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_SIZE 9
#define ZGP_COLOR_DIMMER_SWITCH_CMD_LIST_SIZE 4
#define ZGP_ATTR_REPORT_CMD_LIST_SIZE 4
#define ZGP_ZCL_TUNNELING_CMD_LIST_SIZE 1
#define ZGP_G8CS_1C_CMD_LIST_SIZE 2
#define ZGP_G8CS_2C_CMD_LIST_SIZE 4
#define ZGP_G8CS_3C_CMD_LIST_SIZE 6
#define ZGP_G8CS_4C_CMD_LIST_SIZE 8
#define ZGP_G8CS_5C_CMD_LIST_SIZE 10
#define ZGP_G8CS_6C_CMD_LIST_SIZE 12
#define ZGP_G8CS_7C_CMD_LIST_SIZE 14
#define ZGP_G8CS_8C_CMD_LIST_SIZE 16

#ifdef ZGP_ENABLE_MULTI_SENSOR_SUPPORT
#define ZGP_COMPACT_REPORT_CMD_LIST_SIZE 1
#define ZGP_COMPACT_REPORT_CMD_LIST      ZGP_COMPACT_REPORT_CMD_ID_MAPPING
#else
#define ZGP_COMPACT_REPORT_CMD_LIST_SIZE 0
#define ZGP_COMPACT_REPORT_CMD_LIST
#endif


#ifndef ZGP_NO_OF_OPTION_RECORDS_IN_TRANS_ENTRY
#define ZGP_NO_OF_OPTION_RECORDS_IN_TRANS_ENTRY   3
#endif
/**************************************************************************//**
Application device configuration
******************************************************************************/
#if (APP_ENABLE_ZGP_CERTIFICATION_EXTENSION == 1)
// This configuration is used only for GPD certification purpose(as a TH device)
// where temp. sensor and advanced switch need to be commissioned
// So creating dummy entries for both of them
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST_SIZE 2
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST ZGP_ADVANCED_GENERIC_1_STATE_SWITCH, \
                                         ZGP_TEMPERATURE_SENSOR

// Dummy command list for temp. sensor and advanced switch to avoid compilation error
#define ZGP_ON_OFF_SWITCH_ENABLED
#define ZGP_LEVEL_CONTROL_SWITCH_ENABLED

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE_DEFAULT_SIZE (ZGP_ON_OFF_SWITCH_CMD_LIST_SIZE + \
                                                           ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_SIZE)

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE ZGP_ON_OFF_SWITCH_CMD_LIST, \
                                             ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST

#define ZGP_ON_OFF_SWITCH_CMD_LIST_START_INDEX 0
#define ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_START_INDEX (ZGP_ON_OFF_SWITCH_CMD_LIST_START_INDEX + \
                                                       ZGP_ON_OFF_SWITCH_CMD_LIST_SIZE)
#elif (APP_Z3_DEVICE_TYPE == APP_DEVICE_TYPE_EXTENDED_COLOR_LIGHT) || \
      (APP_Z3_DEVICE_TYPE == APP_DEVICE_TYPE_COLOR_LIGHT)
// Default configuration for EXTENDED_COLOR_LIGHT
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST_SIZE 3
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST ZGP_ON_OFF_SWITCH, \
                                         ZGP_LEVEL_CONTROL_SWITCH, \
                                         ZGP_COLOR_DIMMER_SWITCH

#define ZGP_ON_OFF_SWITCH_ENABLED
#define ZGP_LEVEL_CONTROL_SWITCH_ENABLED
#define ZGP_COLOR_DIMMER_SWITCH_ENABLED

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE_DEFAULT_SIZE (ZGP_ON_OFF_SWITCH_CMD_LIST_SIZE + \
                                                           ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_SIZE + \
                                                           ZGP_COLOR_DIMMER_SWITCH_CMD_LIST_SIZE)

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE      ZGP_ON_OFF_SWITCH_CMD_LIST, \
                                                  ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST, \
                                                  ZGP_COLOR_DIMMER_SWITCH_CMD_LIST

#define ZGP_ON_OFF_SWITCH_CMD_LIST_START_INDEX 0
#define ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_START_INDEX (ZGP_ON_OFF_SWITCH_CMD_LIST_START_INDEX + \
                                                       ZGP_ON_OFF_SWITCH_CMD_LIST_SIZE)
#define ZGP_COLOR_DIMMER_SWITCH_CMD_LIST_START_INDEX  (ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_START_INDEX + \
                                                       ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_SIZE)

#elif (APP_Z3_DEVICE_TYPE == APP_DEVICE_TYPE_DIMMABLE_LIGHT)
// Default configuration for DIMMABLE_LIGHT
#ifdef ZGP_ENABLE_GENERIC_8_CONTACT_SWITCH_SUPPORT
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST_SIZE 3
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST ZGP_ON_OFF_SWITCH, \
                                         ZGP_LEVEL_CONTROL_SWITCH, \
                                         ZGP_GENERIC_8_CONTACT_SWITCH
#else
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST_SIZE 2
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST ZGP_ON_OFF_SWITCH, \
                                         ZGP_LEVEL_CONTROL_SWITCH
#endif // ZGP_ENABLE_GENERIC_8_CONTACT_SWITCH_SUPPORT

#define ZGP_ON_OFF_SWITCH_ENABLED
#define ZGP_LEVEL_CONTROL_SWITCH_ENABLED

#ifdef ZGP_ENABLE_GENERIC_8_CONTACT_SWITCH_SUPPORT
// This macro defines the maximum no of contact supported in this implementation
// it shall be changed to any value from 1 to 8
#define ZGP_NO_OF_CONTACTS_IN_GPD_SWITCH  8 
// This macro is  no of G8C switches commissioned at a time, to remember the order of press
// once all the contacts are commissioned we can commission more than MAX_NO_OF_G8CS_TO_TRACK_ORDER_OF_PRESS 
#define MAX_NO_OF_G8CS_TO_TRACK_ORDER_OF_PRESS    2 
//#define ZGP_GPD_PROCESSING_IN_APPLICATION_SUPPORTED
#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE_DEFAULT_SIZE (ZGP_ON_OFF_SWITCH_CMD_LIST_SIZE + \
                                                           ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_SIZE +\
                                                           ZGP_G8CS_1C_CMD_LIST_SIZE +\
                                                           ZGP_G8CS_2C_CMD_LIST_SIZE +\
                                                           ZGP_G8CS_3C_CMD_LIST_SIZE +\
                                                           ZGP_G8CS_4C_CMD_LIST_SIZE +\
                                                           ZGP_G8CS_1C_CMD_LIST_SIZE) // rocker 1C 

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE ZGP_ON_OFF_SWITCH_CMD_LIST, \
                                             ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST, \
                                             ZGP_G8CS_1C_CMD_LIST, \
                                             ZGP_G8CS_2C_CMD_LIST, \
                                             ZGP_G8CS_3C_CMD_LIST, \
                                             ZGP_G8CS_4C_CMD_LIST, \
                                             ZGP_G8CS_ROCKER_1C_CMD_LIST
#else
#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE_DEFAULT_SIZE (ZGP_ON_OFF_SWITCH_CMD_LIST_SIZE + \
                                                           ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_SIZE)
#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE ZGP_ON_OFF_SWITCH_CMD_LIST, \
                                             ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST
#endif // ZGP_ENABLE_GENERIC_8_CONTACT_SWITCH_SUPPORT

#define ZGP_ON_OFF_SWITCH_CMD_LIST_START_INDEX 0
#define ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_START_INDEX (ZGP_ON_OFF_SWITCH_CMD_LIST_START_INDEX + \
                                                       ZGP_ON_OFF_SWITCH_CMD_LIST_SIZE)
#define ZGP_G8CS_1C_CMD_LIST_START_INDEX               (ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_START_INDEX + \
                                                       ZGP_LEVEL_CONTROL_SWITCH_CMD_LIST_SIZE)
#define ZGP_G8CS_2C_CMD_LIST_START_INDEX               (ZGP_G8CS_1C_CMD_LIST_START_INDEX + \
                                                       ZGP_G8CS_1C_CMD_LIST_SIZE)
#define ZGP_G8CS_3C_CMD_LIST_START_INDEX               (ZGP_G8CS_2C_CMD_LIST_START_INDEX + \
                                                       ZGP_G8CS_2C_CMD_LIST_SIZE)
#define ZGP_G8CS_4C_CMD_LIST_START_INDEX               (ZGP_G8CS_3C_CMD_LIST_START_INDEX + \
                                                       ZGP_G8CS_3C_CMD_LIST_SIZE)
// 5c to 8c are just reusing the commands, so the start index is same as for 1C
//user can change this mapping
#define ZGP_G8CS_5C_CMD_LIST_START_INDEX               (ZGP_G8CS_1C_CMD_LIST_START_INDEX)
#define ZGP_G8CS_6C_CMD_LIST_START_INDEX               (ZGP_G8CS_1C_CMD_LIST_START_INDEX)
#define ZGP_G8CS_7C_CMD_LIST_START_INDEX               (ZGP_G8CS_1C_CMD_LIST_START_INDEX)
#define ZGP_G8CS_8C_CMD_LIST_START_INDEX               (ZGP_G8CS_1C_CMD_LIST_START_INDEX)
#define ZGP_G8CS_ROCKER_1C_CMD_LIST_START_INDEX        (ZGP_G8CS_4C_CMD_LIST_START_INDEX + \
                                                        ZGP_G8CS_4C_CMD_LIST_SIZE)
#define ZGP_G8CS_ROCKER_2C_CMD_LIST_START_INDEX        (ZGP_G8CS_3C_CMD_LIST_START_INDEX)
// 3c to 8c are just reusing the commands, so the start index is same as for 1C
//user can change this mapping
#define ZGP_G8CS_ROCKER_3C_CMD_LIST_START_INDEX        (ZGP_G8CS_1C_CMD_LIST_START_INDEX)
#define ZGP_G8CS_ROCKER_4C_CMD_LIST_START_INDEX        (ZGP_G8CS_1C_CMD_LIST_START_INDEX)
#define ZGP_G8CS_ROCKER_5C_CMD_LIST_START_INDEX        (ZGP_G8CS_1C_CMD_LIST_START_INDEX)
#define ZGP_G8CS_ROCKER_6C_CMD_LIST_START_INDEX        (ZGP_G8CS_1C_CMD_LIST_START_INDEX)
#define ZGP_G8CS_ROCKER_7C_CMD_LIST_START_INDEX        (ZGP_G8CS_1C_CMD_LIST_START_INDEX)
#define ZGP_G8CS_ROCKER_8C_CMD_LIST_START_INDEX        (ZGP_G8CS_1C_CMD_LIST_START_INDEX)


#elif (APP_Z3_DEVICE_TYPE == APP_DEVICE_TYPE_ON_OFF_LIGHT)
// Default configuration for ON_OFF_LIGHT
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST_SIZE 1
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST ZGP_ON_OFF_SWITCH

#define ZGP_ON_OFF_SWITCH_ENABLED

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE_DEFAULT_SIZE ZGP_ON_OFF_SWITCH_CMD_LIST_SIZE

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE ZGP_ON_OFF_SWITCH_CMD_LIST
#define ZGP_ON_OFF_SWITCH_CMD_LIST_START_INDEX 0

#elif (APP_Z3_DEVICE_TYPE == APP_DEVICE_TYPE_COMBINED_INTERFACE)
// Default configuration for COMBINED_INTERFACE
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST_SIZE 3
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST ZGP_OCCUPANCY_SENSOR, \
                                         ZGP_TEMPERATURE_SENSOR, \
                                         ZGP_LIGHT_SENSOR

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE_DEFAULT_SIZE (ZGP_ATTR_REPORT_CMD_LIST_SIZE +\
                                                           ZGP_COMPACT_REPORT_CMD_LIST_SIZE +\
                                                           ZGP_ZCL_TUNNELING_CMD_LIST_SIZE)

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE  ZGP_ATTR_REPORT_CMD_LIST, \
                                              ZGP_ZCL_TUNNELING_CMD_LIST, \
                                              ZGP_COMPACT_REPORT_CMD_LIST


#define ZGP_ATTR_REPORT_START_INDEX 0
#define ZGP_TEMPERATURE_MEASUREMENT_SENSOR_ENABLED
#define ZGP_OCCUPANCY_SENSOR_ENABLED
#define ZGP_ILLUMINANCE_MEASUREMENT_SENSOR_ENABLED

#else
// default configuration . This can be customized based on the device type
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST_SIZE 1
#define ZGP_SUPPORTED_GPD_DEVICE_ID_LIST ZGP_ON_OFF_SWITCH

#define ZGP_ON_OFF_SWITCH_ENABLED

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE_DEFAULT_SIZE ZGP_ON_OFF_SWITCH_CMD_LIST_SIZE

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE ZGP_ON_OFF_SWITCH_CMD_LIST
#define ZGP_ON_OFF_SWITCH_CMD_LIST_START_INDEX 0
#endif

#define ZGP_ADDITIONAL_GPD_CMD_TO_ZCL_CMD_MAPPING_ENTIRES 6

// Manufacturer specific cmds
#ifdef ZGP_SINK_ENABLE_MANUFAC_SPECIFIC_HANDLING
// This is a reference for configuring manufacturer specific cluster/cmd

#define MANU_CMD_1 ZGP_MANUFAC_SPECIFIC_CMD_ID_START
#define MANU_CMD_2 (MANU_CMD_1 + 1)

#define ZGP_MANUFAC_SPECIFIC_GPD_CMD_LIST_SIZE              2
#define ZGP_MANUFAC_SPECIFIC_GPD_CMD1_MAPPING               {MANU_CMD_1,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_ON,0,0x00,0x00}
#define ZGP_MANUFAC_SPECIFIC_GPD_CMD2_MAPPING               {MANU_CMD_2,ONOFF_CLUSTER_ID,ZCL_ON_OFF_CLUSTER_STARTUP_OFF,0,0x00}
#define ZGP_MANUFAC_SPECIFIC_GPD_CMD_LIST  ,ZGP_MANUFAC_SPECIFIC_GPD_CMD1_MAPPING, \
                                           ZGP_MANUFAC_SPECIFIC_GPD_CMD2_MAPPING

// list of supported manufacturer id list
#define ZGP_SUPPORTED_MANUFAC_LIST  0x0104
#define ZGP_MANUFAC_CMD_STARTING_INDEX   (ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE_DEFAULT_SIZE)

#define ZGP_MANUFAC_SPECIFIC_CLUSTER_LIST_SIZE  1
#define ZGP_MANUFAC_SPECIFIC_CLUSTER_ID_1 MANUFAC_SPECIFIC_CLUSTER_ID_START
#define ZGP_MANUFAC_SPECIFIC_CLUSTER_ID_2 (MANUFAC_SPECIFIC_CLUSTER_ID_START + 3)
#define ZGP_MANUFAC_SPECIFIC_CLUSTER_LIST ZGP_MANUFAC_SPECIFIC_CLUSTER_ID_1, \
                                          ZGP_MANUFAC_SPECIFIC_CLUSTER_ID_2

#else
#define ZGP_MANUFAC_SPECIFIC_GPD_CMD_LIST_SIZE 0
#define ZGP_MANUFAC_SPECIFIC_GPD_CMD_LIST
#endif //ZGP_SINK_ENABLE_MANUFAC_SPECIFIC_HANDLING

#define ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE_SIZE (ZGP_GPD_CMD_TO_ZCL_CMD_MAPPING_TABLE_DEFAULT_SIZE + \
                                                   ZGP_MANUFAC_SPECIFIC_GPD_CMD_LIST_SIZE + \
                                                   ZGP_ADDITIONAL_GPD_CMD_TO_ZCL_CMD_MAPPING_ENTIRES)

#endif // ZGP_DISABLE_TRANSLATION_TABLE
#endif //// #if APP_ZGP_DEVICE_TYPE >= APP_ZGP_DEVICE_TYPE_COMBO_BASIC
#endif // _GREENPOWER_SUPPORT_
#endif //_ZGPAPPCONFIG_H
