// DOM-IGNORE-BEGIN
/*******************************************************************************
  Zigbee device object debug Header File

  Company:
    Microchip Technology Inc.

  File Name:
    zdoDbg.h

  Summary:
    This file contains the ZDO constants for debugging and tracing.

  Description:
    This file contains the ZDO constants for debugging and tracing.
 *******************************************************************************/


/*******************************************************************************
* Copyright (C) 2018 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
*******************************************************************************/
// DOM-IGNORE-END

// DOM-IGNORE-BEGIN
#if !defined _ZDO_DBG_H
#define _ZDO_DBG_H
// DOM-IGNORE-END

/******************************************************************************
                              Includes section
 ******************************************************************************/
#include <systemenvironment/include/dbg.h>

/******************************************************************************
                               Types section
 ******************************************************************************/
/** ZDO assert codes. Range 0x5000 - 0x5FFF. */
typedef enum _ZdoDbgCode_t
{
  ZDOSECURITYMANAGER_SECURITYMANAGERHANDLER_0 = 0x5001,
  ZDOSECURITYMANAGER_SECURITYMANAGERHANDLER_1 = 0x5002,
  ZDOSECURITYMANAGER_APSTRANSPORTKEYIND_0 = 0x5003,
  ZDOSECURITYMANAGER_APSAUTHENTICATECONF_0 = 0x5004,
  ZDOSECURITYMANAGER_AUTHENTICATIONSTART_0 = 0x5005,

  ZDONWKMANAGER_SETTXPOWERCONF_0 = 0x5010,
  ZDONWKMANAGER_NWKJOININD_0 = 0x5011,

  ZDOSERVICEDISCOVERY_ZDPDISCOVERYREQUESTCREATE_0 = 0x5020,
  ZDOSERVICEDISCOVERY_ZDPDISCOVERYMESSAGEIND_0 = 0x5021,

  ZDOSTARTNETWORK_STARTNETWORKREQ_0 = 0x5030,
  ZDOSTARTNETWORK_TASKHANDLER_0 = 0x5031,
  ZDOSTARTNETWORK_TASKHANDLER_1 = 0x5032,
  ZDOSTARTNETWORK_TASKHANDLER_2 = 0x5033,
  ZDOSTARTNETWORK_ZDOSTARTNETWORK_0 = 0x5034,
  ZDOSTARTNETWORK_REJOINNETWORK_0 = 0x5035,
  ZDOSTARTNETWORK_SETUPSTARTUPPARAMETERS_0 = 0x5036,
  ZDOSTARTNETWORK_NETWORKFORMATIONCONF_0 = 0x5037,
  ZDOSTARTNETWORK_NWKJOINCONF_0 = 0x5038,
  ZDOSTARTNETWORK_AUTHENTICATIONSUCCESS_0 = 0x5039,
  ZDOSTARTNETWORK_AUTHENTICATIONCONF_0 = 0x503A,
  ZDOSTARTNETWORK_NWKPERMITJOINCONF_0 = 0x503B,
  ZDOSTARTNETWORK_NWKPERMITJOINCONF_1 = 0x503C,
  ZDOSTARTNETWORK_NWKSTARTROUTERCONF_0 = 0x503D,
  ZDOSTARTNETWORK_APSSTARTCONF_0 = 0x503E,

  ZDOLEAVENETWORK_LEAVENETWORK_0 = 0x5040,
  ZDOLEAVENETWORK_LEAVENETWORKIND_0 = 0x5041,
  ZDOLEAVENETWORK_APSSTOPCONF_0 = 0x5042,
  ZDOLEAVENETWORK_LEAVENETWORKNWKLEAVECONF_0 = 0x5043,
  ZDOLEAVENETWORK_NETWORKCONFIRM_0 = 0x5044,

  ZDOPOWERMANAGER_SLEEPREQ_0 = 0x5050,
  ZDOPOWERMANAGER_WAKEUPREQ_0 = 0x5051,
  ZDOPOWERMANAGER_WAKEUPCALLBACK_0 = 0x5052,
  ZDOPOWERMANAGER_SLEEPCONFIRM_0 = 0x5053,
  ZDOPOWERMANAGER_SLEEPCONFIRM_1 = 0x5054,
  ZDOPOWERMANAGER_WAKEUPCONFIRM_0 = 0x5055,
  ZDOPOWERMANAGER_WAKEUPCONFIRM_1 = 0x5056,
  ZDOPOWERMANAGER_TRANSCEIVERSWITCHEDON_0 = 0x5057,

  ZDOENDDEVICEBINDING_ENDDEVICEBINDINGIND_0 = 0x5060,
  ZDOENDDEVICEBINDING_SAVESECONDENDDEVICEBINDINGREQ_0 = 0x5061,
  ZDOENDDEVICEBINDING_ENDDEVICEBINDINGRESPONSECREATE_0 = 0x5062,
  ZDOENDDEVICEBINDING_ENDDEVICEBINDINGRESPONSECREATE_1 = 0x5063,
  ZDOENDDEVICEBINDING_SENDNEXTBINDREQ_0 = 0x5064,
  ZDOENDDEVICEBINDING_ENDDEVICEBINDINGREQUESTCREATE_0 = 0x5065,
  ZDOENDDEVICEBINDING_ENDDEVICEBINDINGREQUESTCREATE_1 = 0x5066,
  ZDOENDDEVICEBINDING_PREPAREFIRSTUNBINDREQ_0 = 0x5067,

  ZDOBINDING_GENERATEUNBINDBINDREQ_0 = 0x5070,
  ZDOBINDING_UNBINDBINDIND_0 = 0x5071,
  ZDOBINDING_UNBINDBINDIND_1 = 0x5072,
  ZDOBINDING_MGMTBINDIND_0 = 0x5073,
  ZDOBINDING_INITDSTADDRESS_0 = 0x5074,

  ZDOINTRAPANPORTABILITY_PERFORMINTRAPANPORTABILITY_0 = 0x5080,

  ZDOPERMISSIONSTABLE_SETPERMISSIONS_0 = 0x5090,
  ZDOPERMISSIONSTABLE_UPDATEPERMISSIONS_0 = 0x5091,
  ZDOPERMISSIONSTABLE_GETPERMISSIONS_0 = 0x5092,
  ZDOPERMISSIONSTABLE_DELETEPERMISSIONS_0 = 0x5093,
  ZDOPERMISSIONSTABLE_ACCESSREQHANDLER_0 = 0x5094,

  ZDO_ADDRESS_RESOLVING_0 = 0x50A0,
  ZDO_ADDRESS_RESOLVING_1 = 0x50A1,
  ZDO_ADDRESS_RESOLVING_2 = 0x50A2,
  ZDO_ADDRESS_RESOLVING_3 = 0x50A3,
  ZDO_ADDRESS_RESOLVING_4 = 0x50A4,

  ZDOINIT_ZDOINITRESETNETWORKCONF_0 = 0x50B0,

  ZDOZDPREQ_HANDLER_0 = 0x50C0,
  ZDOZDPREQ_HANDLER_1 = 0x50C1,
  ZDOZDPREQ_HANDLER_2 = 0x50C2,
  ZDOZDPREQ_HANDLER_3 = 0x50C3,
  ZDOZDPREQ_HANDLER_4 = 0x50C4,
  ZDOZDPREQ_HANDLER_5 = 0x50C5,
  ZDOZDPREQ_ZDOZDPAPSCONFCALLBACK_0 = 0x50C6,
  ZDOZDPREQ_ZDOZDPAPSCONFCALLBACK_1 = 0x50C7,
  ZDOZDPREQ_PREPAREZDPREQUEST_0 = 0x50C8,

  ZDONODEMANAGER_PERMITJOININGCONF_0 = 0x50D0,
  ZDONODEMANAGER_ZDOZDPNODEREQUESTCREATE_0 = 0x50D1,
  ZDONODEMANAGER_NODEMESSAGEIND_0 = 0x50D2,

  ZDOCOMMANDS_FREECOMMAND_0 = 0x50E0,
  ZDOCOMMANDS_FREECOMMAND_1 = 0x50E1,
  ZDOCOMMANDS_INITZDPCOMMAND_0 = 0x50E2,
  ZDOCOMMANDS_APSZDODATAIND_0 = 0x50E3,
  ZDOCOMMANDS_ZDPPREPARERESPONSE_0 = 0x50E4,

  ZDORESET_STACKRESETCONF_0 = 0x50F0,
  ZDORESET_RESETNETWORKREQ_0 = 0x50F1,

  ZDOTASKMANAGER_TASKHANDLER_0 = 0x5100,

  ZDOMGMTNWKUPDATE_NOTIFYCONF_0 = 0x5110,
  ZDOMGMTNWKUPDATE_CHANNELCHANGETIMERFIRED_0 = 0x5111,
  ZDOMGMTNWKUPDATE_SENDNWKUPDATENOTIFY_0 = 0x5112,
  ZDOMGMTNWKUPDATE_MACSETCONF_0 = 0x5113,
  ZDOMGMTNWKUPDATE_MACSETCONF_1 = 0x5114,
  ZDOMGMTNWKUPDATE_EDSCANCONF_0 = 0x5115,
  ZDOMGMTNWKUPDATE_MGMTNWKUPDATENOTIFYCONF_0 = 0x5115,
  ZDOMGMTNWKUPDATE_PREPAREMGMTNWKUPDATENOTIFY_0 = 0x5116,

  ZDOSECURITYMANAGER_APSVERIFYKEYREQ_0 = 0x5117,
  ZDOSECURITYMANAGER_APSVERIFYKEYREQ_1 = 0x5118,
} ZdoDbgCode_t;

#endif /* _ZDO_DBG_H */
/** eof zdoDbg.h */
