/*******************************************************************************
  PHY Initialisation Header File

  Company:
    Microchip Technology Inc.

  File Name:
    phyInit.h

  Summary:
    This file contains the Radio Transceiver Initialization.

  Description:
    This file contains the Radio Transceiver Initialization.
 *******************************************************************************/

// DOM-IGNORE-BEGIN
/*******************************************************************************
* Copyright (C) 2018 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
*******************************************************************************/
// DOM-IGNORE-END

#ifndef _PHYINIT_H
#define _PHYINIT_H

/******************************************************************************
                    Define(s) section
******************************************************************************/
#define MAX_WAITING_TIME 2000

/******************************************************************************
                    Prototypes section
******************************************************************************/
/******************************************************************************
  Initializes radio transciever.
  Parameters: none.
  Returns: status operation.
******************************************************************************/
bool PHY_Init(void);

/******************************************************************************
  Set external frequency generated by RF chip.
  Parameters: none.
  Returns: none.
******************************************************************************/
void phySetFreq(void);
/******************************************************************************
  Checks RF is in a state for any upper layer operation and change accorginly
  Parameters:
    none
  Return: true or false
******************************************************************************/
bool PHY_ZBIsIdle(void);
/******************************************************************************
  To set back the PHY state to Idle for Normal RF Operation
  Parameters:
    none
  Return: None
******************************************************************************/
void PHY_ZBSetIdle(void);

#endif /*_PHYINIT_H*/

// eof phyInit.h
